### ISSUE TITLE
Unable to Update Supervisor via Dashboard

### ISSUE THREAD

**Issue by Sourcer63** [HuckleberryLovesYou/Homeassistant-Supervised-on-Raspberry-Pi-5#13]
HA has released a new Supervisor version 2024.10. 

I am uncertain how to manually run the update. Can I simply update supervisor by repeating the wge part where the supervisor deb file is downloaded and then installed?

Before damaging the setup I thought it might be better to ask first. Maybe you could amend the readme file.

EDIT:  The initial attempt to update within HA threw an error. Meanwhile the installation did update itself. 🤷

**Comment by Sourcer63** [comment]
Problem! 
After a full restart of the RPi5 the HA setup opens in safe mode. No way to repair it other than restoring the full backup.

So the question pertains: how can one update to a new Supervisor version?

**Comment by HuckleberryLovesYou** [comment]
Hi, thanks for opening a issue.

Could you please provide us with the logs by Homeassistant as a pastebin link or as a code block in your response?

Furthermore, could you provide following informations:
- What Version did you update from?
- What OS are you running
- Are you running Portainer as well as Homeassistant (and what name has the container)?
- What Hardware is Homeassistant running on? 
- Did you change something in the configuration.yaml since the last reboot of home assistant or device? 
Best regards

**Comment by Sourcer63** [comment]
Hi Tim,
prior to the issue I had a fully functional 2024.09 supervisor setup. HA notified me of three available updates (Supervisor 2024.10 plus two integrations). Suspicious that Supervisor might cause issues, I tried to update the integrations. This failed because of an outdated Supervisor. Some time later, the system suddenly displayed Supervisor having updated itself to 2014.10. 

Because of a hardware update on the RPi (new USB device requiring a driver), I rebooted the system after which HA started in Safe Mode as described above. I then restored a 2024.09 backup. HA Supervisor updated itself again to 2024.10. I have not dared to restart yet. The attached logs show the current situation.

- Updated from HA 2024.09.1 and SV 2024.09
- OS is Raspberry Pi OS
- No Portainer
- HA is installed on a RPi5
- No changes in configuration.yaml, some new thing in automations

[host_2024-10-08T15-51-20.213Z.log](https://github.com/user-attachments/files/17295980/host_2024-10-08T15-51-20.213Z.log)
[home-assistant_2024-10-08T15-50-42.219Z.log](https://github.com/user-attachments/files/17295981/home-assistant_2024-10-08T15-50-42.219Z.log)
[supervisor_2024-10-08T15-58-04.453Z.log](https://github.com/user-attachments/files/17295990/supervisor_2024-10-08T15-58-04.453Z.log)

Thanks for your help - and your great work. Pity that the Home Assistant people are so critical towards such a setup.

**Comment by Sourcer63** [comment]
I dared to restart HA: no problem. Wondering what went wrong before. 

Today's breakdown caused a few hours of lost work by having to go back to the previous full backup. Since I am in the process of migrating a large LCN and Homematic smarthome setup to HomeAssistant, I remain cautious. Anyway, it looks stable now, although I still need to test a reboot rather than simply a HA restart.

**Comment by HuckleberryLovesYou** [comment]
Hey, great that you were able to solve this issue.

I wonder where that happend. The logs seem okay from my perspective. I tried updating yesterday as well and it worked like a charm.

I'm sorry that I wasn't able to help you out with that error.

If it happens again e. g. at the next updats, feel free to reopen this issue.
