### ISSUE TITLE
After install No Video in Chromium

### ISSUE THREAD

**Issue by Bollemp3** [HuckleberryLovesYou/Homeassistant-Supervised-on-Raspberry-Pi-5#4]
I have now done the installation twice on a clean installation and before the installation all streams within chromium work, but unfortunately nothing anymore after the installation. Not Netflix but also other sites.
The first image of the video is shown, then the image remains frozen. The player 'plays' but no audio and no image.

How can i fix this?

**Comment by HuckleberryLovesYou** [comment]
I never tested if playing a video still works, because I've only the cli-editon installed. Also known as the raspberrian OS Lite 64bit. With that I sadly won't be able to give you a solution for that error. I'm sorry.

**Comment by Bollemp3** [comment]
Thanks for the great manual, everything works perfectly now! 

I found the problem, the audio card is used by Home Assistant. 

Fixed by download a third party add-on “Alsa & PulseAudio Fix”… quick and really dirty… but it works.

It kills the audio of home assistant.

**Comment by HuckleberryLovesYou** [comment]
That's great to hear!
Thanks for your feedback!
